################################################################################
# Goal: Plot RTT, LTT and Q_rates in a fancy way
# Authors: Alexis Marion and Lucas Buffan (Lucas.L.Buffan@gmail.com)
# Description :
#   args[1] => type of analysis carried out
#   args[2] => path towards the RTT_plots.R script generated by PyRate after the -plot command
#   args[3] => path towards the directory where LTT per replicates are stored
#   args[4] => path towards the "Parse_Q_rates.csv" file storing the q values per time bin (TPP)
#   args[5] => output rate plot name and directory
#   args[6] => output freq rate shifts plot name and directory
#   args[7] => where are the accessory function scripts stored
# Note : ONLY RUN IN COMMAND LINES
################################################################################

library("hash")
library("DDD")
library("readxl")
library("dplyr")

args <- commandArgs(trailingOnly=TRUE)

## Source accessory functions for plotting -------------------------------------
source(paste0(args[7], "/1-extract_param_from_PyRate_outputs.R"))
source(paste0(args[7], "/2-plotting_facilities.R"))
SALMA <- read_xlsx("../data_2023/time_bins/SALMA_EOT.xlsx")
SALMA <- SALMA %>% rename(min_age = "min_ma", max_age = "max_ma", name = "interval_name")

ana <- args[1] #ana = 'RJMCMC' or 'BDS'

## Diversification rates -------------------------------------------------------
  # Get diversification rates table
rtt_all_in_one <- extract_rtt(args[2], ana = ana)
  # Origination and Extinction rates plot
sp_ex_all_in_one <- rtt_plot(data = rtt_all_in_one,
                             type = "SpEx",
                             y_limits = c(0, 1.5),
                             several_gts = TRUE,
                             geoscale2 = SALMA,
                             abbr = list(TRUE, FALSE))

  # Net diversification rate plot
net_div_all_in_one <- rtt_plot(data = rtt_all_in_one,
                               type = "net",
                               several_gts = TRUE,
                               geoscale2 = SALMA,
                               abbr = list(TRUE, FALSE))

## Lineages-through-time (LTT)--------------------------------------------------
  # LTT table
ltt_df <- extract_ltt(dir = args[3])
ltt_df <- ltt_df %>% filter(Age > 23.03 & Age < 56) # erase what's outside study period
  # LTT plot
ltt.plot <- ltt_plot(ltt_df, 
                     y_breaks = seq(0,(round(max(ltt_df$Diversity), -1) + 10),30), 
                     y_limits = c(0,(round(max(ltt_df$Diversity), -1) + 20)),
                     several_gts = TRUE,
                     geoscale2 = SALMA,
                     abbr = list(TRUE, FALSE))

## Preservation (q) rates ------------------------------------------------------
  # q-rates table
omega<-read.table(args[4], header = TRUE)
omega <- omega %>% filter(Age > 23.03 & Age < 56)
  # q-rates plot
Q_plot<-q_plot(omega, 
               ltt_df,
               several_gts = TRUE,
               geoscale2 = SALMA,
               abbr = list(TRUE, FALSE))

## Combine all these plots and save the output ---------------------------------
p <- comb_ltt_rtt(sp_ex_all_in_one, net_div_all_in_one, ltt.plot, Q_plot, n_plots = 4)
ggsave(args[5],
           plot = p,
           height = 350,
           width = 450,
           units = "mm",
           dpi = 300)

## Frequency of rate shift -----------------------------------------------------
f_rate_shift_tbl <- extract_histo_tbl(args[2])
plot_list <- freq_rate_shift(data = f_rate_shift_tbl[[1]],
                             bf2 = f_rate_shift_tbl[[2]],
                             bf6 = f_rate_shift_tbl[[3]],
                             x_annots = 53.5,
                             y_annot_bf2 = 0.04,
                             y_annot_bf6 = 0.19,
                             x_breaks = c(27.82, 33.9, 37.71, 47.8),
                             x_limits = c(55.5, 23.53), #interesting to custrom to avoid edge effects
                             y_limits = c(0, 0.5),
                             several_gts = TRUE,
                             geoscale2 = SALMA,
                             abbr = list(TRUE, FALSE))
## Combine and save ------------------------------------------------------------
cb <- cowplot::plot_grid(plot_list[[1]], plot_list[[2]],
                         ncol = 2,
                         rel_widths = c(1/2, 1/2))
ggsave(args[6],
       plot = cb,
       height = 250,
       width = 450,
       units = "mm",
       dpi = 300)