################################################################################
# Goal: Plot RTT, LTT and Q_rates in a fancy way
# Authors: Alexis Marion and Lucas Buffan (Lucas.L.Buffan@gmail.com)
# Description :
#   args[1] => type of analysis carried out
#   args[2] => path towards the RTT_plots.R script generated by PyRate after the -plot command
#   args[3] => path towards the directory where LTT per replicates are stored
#   args[4] => path towards the "Parse_Q_rates.csv" file storing the q values per time bin (TPP)
#   args[5] => output file name and directory
#   args[6] => where are the accessory function scripts stored
# Note : ONLY RUN IN COMMAND LINES
################################################################################

library("hash")
library("DDD")
library("readxl")
library("dplyr")

args <- commandArgs(trailingOnly=TRUE)

## Source accessory functions for plotting -------------------------------------
source(paste0(args[6], "/1-extract_param_from_PyRate_outputs.R"))
source(paste0(args[6], "/2-plotting_facilities.R"))
SALMA <- read_xlsx("../data_2023/time_bins/SALMA_EOT.xlsx")
SALMA <- SALMA %>% rename(min_age = "min_ma", max_age = "max_ma", name = "interval_name")

ana <- args[1] #ana = 'RJMCMC' or 'BDS'

## Diversification rates -------------------------------------------------------
  # Get diversification rates table
rtt_all_in_one <- extract_rtt(args[2], ana = ana)
  # Origination and Extinction rates plot
sp_ex_all_in_one <- rtt_plot(data = rtt_all_in_one,
                             type = "SpEx",
                             y_limits = c(0, 1.5),
                             several_gts = TRUE,
                             geoscale2 = SALMA,
                             abbr = list(TRUE, FALSE))

  # Net diversification rate plot
net_div_all_in_one <- rtt_plot(data = rtt_all_in_one,
                               type = "net",
                               several_gts = TRUE,
                               geoscale2 = SALMA,
                               abbr = list(TRUE, FALSE))

## Lineages-through-time (LTT)--------------------------------------------------
  # LTT table
ltt_df <- extract_ltt(dir = args[3])
  # LTT plot
ltt.plot <- ltt_plot(ltt_df, 
                     y_breaks = seq(0,(round(max(ltt_df$Diversity), -1) + 10),30), 
                     y_limits = c(0,(round(max(ltt_df$Diversity), -1) + 20)),
                     several_gts = TRUE,
                     geoscale2 = SALMA,
                     abbr = list(TRUE, FALSE))

## Preservation (q) rates ------------------------------------------------------
  # q-rates table
omega<-read.table(args[4], header = TRUE)
  # q-rates plot
Q_plot<-q_plot(omega, 
               ltt_df,
               several_gts = TRUE,
               geoscale2 = SALMA,
               abbr = list(TRUE, FALSE))

## Combine all these plots and save the output ---------------------------------
p <- comb_ltt_rtt(sp_ex_all_in_one, net_div_all_in_one, ltt.plot, Q_plot, n_plots = 4)
ggsave(args[5],
           plot = p,
           height = 350,
           width = 450,
           units = "mm",
           dpi = 300)
