---
title: "Details for fossil data hand-cleaning based on authors' expertise."
author:
  - "---"
  - Lucas Buffan^1,2^, Laurent Marivaux^2^, Pierre-Olivier Antoine^2^ and Fabien L. Condamine^2^
  - "---"
  - "^1^Département de Biologie, École Normale Supérieure de Lyon, Université Claude Bernard Lyon 1, 69342 Lyon Cedex 07, France."
  - "^2^CNRS, UMR 5554 Institut des Sciences de l’Évolution de Montpellier, Place Eugène Bataillon, 34095 Montpellier, France."
  - "---"
  - "**Corresponding author:** Lucas.L.Buffan@gmail.com"
format:
  docx:
    reference-doc: template.docx
    highlight-style: github
bibliography: references.bib
csl: biology-letters.csl
editor: 
  markdown: 
    wrap: 72
---

# Artiodactyla

*Palaeolama sp.* (coll. nb. 213138, [@rusconi1949]), *Lama castelnaudi* (coll. nb. 213136, [@rusconi1949]) and *Palaeolama weddeli* (coll. nb. 213136, [@rusconi1949]) age ranges were set to Early Pleistocene, according to [@pascual1965].  
All *Bos taurus* and *Ovis* occurrences were removed, as representatives were introduced by humans.  
*Antifer crassus* (coll. nb. 53926, [@rusconi1934]) time range was set to Pleistocene according to [@croitor2022].
*Platygonus narinoensis* (coll. nb. 133585, [@stirton1947]) was renamed *Platygonus cf. marplatensis* according to [@gasparini2021].  
All occurrences of *Cervus gouazoubira* were renamed *Mazama gouazoubira*.


# Astrapotheria

*Grypolophodon imperfectus* (coll. nb. 176290, [@simpson1967]) was removed as nomen dubium.  
*Parastrapotherium holmbergi* (coll. nb. 176290, [@roth1904]) formation was set to Sarmiento, stage to Deseadan-Colehuehuappian, and age range to 20-29 Ma.  
*Xenastrapotherium sp.* (coll. nb. 55602, [@frailey1986]) and *Xenastrapotherium amazonense* (coll. nb. 55602, [@ribeiro2013]) were reassigned to Laventan stage (11.8-13.8 Ma) according [@goillot2011].  
*Notorhinus denticulatus* (coll. nb. 176290, [@roth1904]) removed as nomen dubium.
*Astrapotherium* (coll. nb. 50074, [@tournouer1903]) re-assigned to Santacrucian.

# Carnivora

Removed *Felis domesticus* (coll. nb. 190846, [@steadman1986]) as introduced by humans.

# Cetacea

# Cingulata

# Chiroptera

# Didelphimorphia

# Litopterna

*Archaeohyracotherium mediale* (*Didolodontidae*, coll. nb. 176164, [@simpson1967]) was synonymised with *Asmithwoodwardia subtrigona* (*Protolipternidae*) by Gelfo (2006)[@gelfo2006].  
*Argyrolambda conidens* was synonymised with *Didolodus multicuspis* [@gelfo2006].  
*Didolodus sp.* (coll. nb. 199563, [@antoine2021]) was removed as associated to "unidentified *Didolontidae*" in the paper.
*Enneoconus parvidens* (coll. nb 176164, [@simpson1948]) was synonymised with *Ernestokokenia nitida* by Gelfo (2006)[@gelfo2006].

# Microbiotheria

# Notoungulata

# Paucituberculata

# Perissodactyla

*Equus sp.* (coll. nb. 142016, [@boule1920]) was set to *Equus (Amerhippus)*. Together with *Equus sp.* (coll. nb. 71275, [@rolim1974]; coll. nb. 70673, [@oliveira2017]; coll. nb. 92814, [@salles2006]), *Equus (Amerhippus)* (coll. nb. 70673, [@marshall1991]) and *Hippidion sp.* (coll. nb. 70673, [@marshall1991]), their upper time boundary were set to 0.99 Ma, according to MacFadden (2013) [@macfadden2013].  
*Equus sp.* (coll. nb. 142158 and 142160, [@coltorti2007]) were both set to *Equus (Amerhippus)*.   
*Equus asinus* (coll. nb. 190844, [@steadman1986]) was removed as introduced by humans.  
*Equus caballus* (coll. nb. 63337, [@deschamps2005]) was set *Equus (Amerhippus) neogeus* by Alberdi and Prado (1992) [@alberdi1992].  
*Equus caballus* (coll. nb. 70704, [@marshall1991]) time range was set to Holocene.  
*Equus caballus* (coll. nb. 142016, [@boule1920]) was set to *Equus (Amerhippus) insulatus*.  
*Equus caballus* (coll. nb. 73842, [@oliver1935]) time range was set to Pleistocene by [@canto2010].  
*Equus santaeelenae* (coll. nb. 144922, 145506, [@pujos2004]) time ranges were adjusted to Late Pleistocene.  
*Hippidium (Plagiohippus)* (coll. nb. 71304, [@reig1957]) name was set to *Hippidion* [@alberdi1992].  
*Hypohippidium humahuaquense* (coll. nb. 210722, [@de1957]) was synonymised with *Hippidion devillei* by [@alberdi1992]
*Hippidion sp.* (coll. nb. 73842, [@oliver1935]; coll. nb. 199157, [@cione1996]; coll. nb. 53926, [@rusconi1934], 2 occurrences) time ranges were adjusted to Pleistocene.  
*Tapirus (Tapilarum)* (coll. nb. 53928, [@rusconi1934]) name was shortened to *Tapirus*, and age set to Early Pleistocene.  
*Tapirus oliverasi* (coll. nb. 146534, [@ubilla1983]) species name was removed as doubtful [@holanda2012], occurrence therefore renamed *Tapirus*.
*Tapirus tarijensis* (coll. nb. 70673, [@marshall1991]) lower age boundary was set to 1.06 Ma.  


# Pilosa

# Primates

# Proboscidea

*Mastotherium hyodon* (coll. nb. 142016, [@boule1920] and 145181, [@schneider1927]) genus named was set to *Cuvieronius*.   
*Stegomastodon sp.* (coll. nb. 211646, [@ubilla2009]) was synonymised with *Notiomastodon platensis*.  
All mentions of *Mammut* were removed.  
*Notiomastodon platensis* (coll. nb. 144515, [@campbell2000]), formerly described as *Amahuacatherium peruvianum* was removed as its age was questioned in [@negri2009].

# Rodentia 
## Added Occurrences
*Ricardomys longidens*, Laventan age, San Martín department, Peru [@boivin2021].  
*Microscleromys sp.* (two occurrences), *Microscleromys cribriphilus*, *Microscleromys paradoxalis*, *Microsteiromys jacobsi*, *Nuyuyomys chinqaska*, *Scleromys*, Laventan age, San Martín department, Peru [@boivin2021].  
*Balsayacuy sp.*, Rupelian age (restricted to the 27.82-31.1 Ma interval), Departamento de Ucayali, Santa Rosa locality, Peru [@arnal2022]. Described as an occurrence of *Balsayacuy huallagaensis*, but species attribution doubtful. Hence, restricted to genus level. From the same paper (same locality and same age), we also add one occurrence of *Shapajamys minor*, one of *Ucayalimys amahuacensis* and one of *Vucetichimys pterilophodonica*.  
*Erethizon sp.*, Vorohuean (Marplatan) age, Uquía formation, Quebrada de Humahuaca locality, Jujuy state, Argentina [@reguero2007].  
*Eoincamys valverdei* and *Tarapotomys subandinus*, Early Oligocene of resp. TAR-72 and TAR-22, San Martín, Peru [@boivin2018].  

## Corrections
*Cachiyacuy contamanensis* (coll. nb. 149523, [@arnal2020]) was renamed *Cachiyacuy sp.* as taxonomic assignation under debate. Two *Cachiyacuy contamanensis* occurrences from the same collection, same paper, were renamed *cf. Cachiyacuy contamanensis*, for the same reason.  
*Kichkasteiromys raimondii*: age range set to 34-35 Ma.  
Time boundaries of *Cachiyacuy cf. contamanensis* and *Cachiyacuy contamanensis* (coll. nbs. 207061 and 207062, [@assemat2019]) were set to Priabonian (33.9-37.2 Ma). Same for *Cachiyacuy cf. kummeli*, *Eoespina* and *cf. Eoespina* (coll. nb. 207062, 207062 and 207065, [@assemat2019]) Remaning occurrences of the genus *Cachiyacuy* (four in total) were set to Late-Middle Eocene (33.9-41.2 Ma).  
*Canaanimys maquiensis* (coll. nb. 149523, [@arnal2020]) was renamed *Canaanimys sp.* as taxonomic assignation under debate.

Time boundaries of four *Cachiyacuy kummeli* occurrences (coll. nb. 144474, [@antoine2012]; 176136, [@boivin2017], 207067 and 207062 [@assemat2019]) were set to Late-Middle Eocene (33.9-41.2 Ma). Same for *Eobranisamys sp.* (coll. nb. 176151, [@boivin2017]) and for all occurrences from the 144474 collection, including one *Chachapoyamys cf. kathetos* [@boivin2021], one *Eoespina sp.* [@antoine2012], one *Canaanimys maquiensis* [@antoine2012] and one *Eobranisamys javierpardoi* [@boivin2017].      
Ages of all occurrences from the collection 149523 were restricted to Rupelian. These included two *cf. Cachiyacuy kummeli* occurrences [@arnal2020], one *Canaanimys sp.* [@arnal2020], one *Eobranisamys riverai*, one *Eobranisamys romeropittmanae*, one *Eoespina woodi*, one *Eoincamys ameghinoi*, one *Eoincamys pascuali*, one *Eopicure kraglievichi*, one *Eosachacui lavocati*, one *Eosallamys paulacoutoi*, one *Eosallamys simpsoni* [@frailey2004], one *Pozomys sp.*, two *Pozomys ucayalensis* [@arnal2020], one *Eodelphomys almeidacomposi*, one *Eopululo wigmorei* [@frailey2004].  
Ages of two *Sallamys pascuali* occurrences (coll. nb. 95688, [@lavocat1976]; 133539, [@patterson1982]), three *Branisamys luribayensis* (coll. nb. 95688 [@lavocat1976]; 95688 [@hartenberger1975]; 133539 [@patterson1982]) were sharpened to the 25-26 Ma interval.  
Ages of one *Pozomys ucayalensis* (coll. nb. 176129, [@boivin2017]) were set to Late Eocene (33.9-41.2 Ma). 
Ages of two *Eoespina sp.* occurrences (coll. nb. 176140, [@boivin2017]) was restricted to Late Eocene.  
Ages of one *Eoespina* and one *cf. Eoespina* occurrence (coll. nb. 207062 and 207065, [@assemat2019]) were set to Rupelian.  
*Eoincamys pascuali* (coll. nb. 207064, [@assemat2019]) was renamed *Eonincamys sp.*.
Age range of all Late Oligocene occurrences from the Salla formation, La Paz, Bolivia, was set to 24.5-26 Ma.
*Eopululo wigmorei* (coll. nb. 225588, [@antoine2021]) species name was set to *Eopululo sp.* according to [@boivin2021].  
Names of all *Eumysops chapalmalensis* occurrences were set to *Eumysops chapadmalensis*.

## Removed occurrences
*Cachiyacuy kummeli* (coll. nb. 207067, [@assemat2019]), renamed *C. cf. kummeli* (doublon) according to [@boivin2021].  
*Canaanimys sp.* (coll. nb. 176136, [@antoine2016]), taxonomic revision [@boivin2021].  
*Canaanimys maquiensis* (two occurrences, coll. nb. 207066 and 207067, [@assemat2019]), taxonomic revision [@boivin2021].  
*Chachapoyamys kathetos* (coll. nb. 207067, [@boivin2021]), re-assigned to *C. cf. kathetos* (doublon) [@boivin2021].  
Four Brazilian occurrences of the genera *Eobranisamys* (two) and *Eoincamys* (two) with absurd ages (coll. nb. 57989, [@kerber2017]; coll. nb. 217834, [@lacerda2021]).  
*Tarapotomys sp.* (2 occurrences) (coll. nb. 199560, [@boivin2018]; coll. nb. 199563, [@antoine2021]), respectively re-described as *aff. Tarapotomys sp.* and *Tarapotomys subandinus* in [@boivin2021].  
*Incamys bolivianus* (coll. nb. 95688, [@lavocat1976]), doulon.  
*Asteromys bolivianus* (coll. nb. 133591, [@perez2019]), doublon.  
All *Rattus rattus* occurrences, as introduced by humans.

# Sparassodonta 

# Xenungulata

\newpage
# References